---
contentdir: "content"
layoutdir: "layouts"
publishdir: "xuxianmei.github.io"
taxonomies:  
  category: "categories"

baseurl: "https://xuxianmei.github.io/"
title: "TJoy's Blog"
canonifyurls: true
---